services:
  product_service:
    image: 'postgres:16'
    container_name: product_service_postgres_container
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d product_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: product_db
    ports:
      - "5431:5432"
    volumes:
      - product_data:/var/lib/postgresql/data


volumes:
  product_data:
