server:
  port: 8082
spring:
  application:
    name: cartService
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/cart_db
    username: user
    password: pass123
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db-changelog-master.yaml

logging:
  level:
    org:
      springframework:
        security: debug
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    config-url: /api/cart-service/v3/api-docs/swagger-config
    url: /api/cart-service/v3/api-docs

gateway:
  base-url: http://localhost:8080/api/cart-service
  api-description: Swagger UI Documentation for Cart Service
