spring:
  application:
    name: productService
  port: 8080
  security:
    oauth2:
      resourceServer:
        jwt:
          issuer-uri: http://localhost:8443/realms/ecommerce

frontend:
  url: http://localhost:5173
