server:
  port: 8081
spring:
  application:
    name: productService
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5431/product_db
    username: user
    password: pass123
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db-changelog-master.yaml

logging:
  level:
    org:
      springframework:
        security: debug
management:
  endpoints:
    web:
      exposure:
        include: gateway,health,info
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    config-url: /api/product-service/v3/api-docs/swagger-config
    url: /api/product-service/v3/api-docs
gateway:
  base-url: http://localhost:8080/api/product-service
  api-description: Swagger UI Documentation for Product Service
